### ISSUE TITLE
ora_fields is infinitely recursive

### ISSUE THREAD

**Issue by sigurdurthorjonsson** [fishvice/xe#2]
xe::ora_fields is recursive:

 ora_fields(con,"fiskar.numer")
Error: evaluation nested too deeply: infinite recursion / options(expressions=)?
Error during wrapup: evaluation nested too deeply: infinite recursion / options(expressions=)?
Error: no more error handlers available (recursive errors?); invoking 'abort' restart

is it possible 'xe:::tbl_mar' should replace the mother function in line starting with:

ora_fields(con, "sys.all_col_comments") %>% dplyr::filter(owner ==

**Comment by einarhjorleifsson** [comment]
fixed
